
DROP SEQUENCE S_SEQ;
DROP TABLE SCHEDULE_TABLE;

SELECT *
	FROM (SELECT (ROW_NUMBER() OVER (PARTITION BY SUBSTR(S_DATE,1,10) ORDER BY S_DATE)) 
	RN, S_SEQ, U_NO, D_NO, S_NO, S_DATE, S_TIME, S_LOCATION, S_COURSE, S_PEOPLE, S_PRICE, S_REGDATE, S_LATITUDE, S_LONGITUDE, S_CONFIRMED_CHECK
			FROM SCHEDULE_TABLE WHERE U_NO = 4 AND SUBSTR(S_DATE,1,7)= '2018-12' )
	WHERE RN BETWEEN 1 AND 3;

	
	
CREATE SEQUENCE S_SEQ;
CREATE TABLE SCHEDULE_TABLE(
	S_SEQ NUMBER PRIMARY KEY,
	U_NO NUMBER NOT NULL,
	D_NO NUMBER NOT NULL,
	S_NO NUMBER NOT NULL,
	S_DATE VARCHAR2(100) NOT NULL,
	S_TIME NUMBER NOT NULL,
	S_LOCATION VARCHAR2(1000) NOT NULL,
	S_COURSE VARCHAR2(1000) NOT NULL,
	S_PEOPLE NUMBER NOT NULL,
	S_PRICE VARCHAR2(100) NOT NULL,
	S_REGDATE DATE NOT NULL,
	S_LATITUDE VARCHAR2(1000) NOT NULL,
	S_LONGITUDE VARCHAR2(1000) NOT NULL,
	S_CONFIRMED_CHECK VARCHAR2(2) NOT NULL,
	CONSTRAINT U_NO_FK FOREIGN KEY(U_NO) REFERENCES USER_TABLE(U_NO),
	CONSTRAINT D_NO_FK FOREIGN KEY(D_NO) REFERENCES DRIVER_TABLE(D_NO),
	CONSTRAINT S_CONFIRMED_CHECK_CK CHECK (S_CONFIRMED_CHECK IN ('Y','N','P'))
);

SELECT * FROM SCHEDULE_TABLE;

SELECT US.U_NO, US.U_NAME, US.U_PHONE, SH.D_NO, DR.D_PROFILE, DR.D_REGION, DR.D_NAME, DR.D_BIRTH, DR.D_GENDER, DR.D_TITLE, DR.D_CONTENT, SH.U_NO, SH.S_SEQ, SH.S_DATE, SH.S_TIME, SH.S_LOCATION, SH.S_COURSE, SH.S_PEOPLE, SH.S_PRICE, SH.S_REGDATE, SH.S_LATITUDE, SH.S_LONGITUDE, SH.S_CONFIRMED_CHECK, RA_RATING
	FROM SCHEDULE_TABLE SH
	JOIN DRIVER_TABLE DR
	ON SH.D_NO = DR.D_NO
	JOIN USER_TABLE US
	ON SH.U_NO = US.U_NO
	JOIN (SELECT AVG(RA_RATING) AS RA_RATING, D_NO FROM RATING_TABLE GROUP BY D_NO) RA
	ON DR.D_NO = RA.D_NO
	WHERE SH.S_SEQ = 1;
	
SELECT US.U_NO, US.U_NAME, US.U_PHONE, SH.D_NO, DR.D_PROFILE, DR.D_REGION, DR.D_NAME, DR.D_BIRTH, DR.D_GENDER, DR.D_TITLE, DR.D_CONTENT, SH.U_NO, SH.S_SEQ, SH.S_DATE, SH.S_TIME, SH.S_LOCATION, SH.S_COURSE, SH.S_PEOPLE, SH.S_PRICE, SH.S_REGDATE, SH.S_LATITUDE, SH.S_LONGITUDE, SH.S_CONFIRMED_CHECK, RA_RATING
	FROM SCHEDULE_TABLE SH
	JOIN DRIVER_TABLE DR
	ON SH.D_NO = DR.D_NO
	JOIN USER_TABLE US
	ON SH.U_NO = US.U_NO
	LEFT OUTER JOIN (SELECT AVG(RA_RATING) AS RA_RATING, D_NO FROM RATING_TABLE GROUP BY D_NO) RA
	ON DR.D_NO = RA.D_NO
	WHERE SH.S_SEQ = 5;	


INSERT INTO SCHEDULE_TABLE 
VALUES(S_SEQ.NEXTVAL,4,2,1,'2018-12-24' ,'8','제주도','동백습지 -> 한라산 -> 우도 -> 샤려니숲길',2,'100,000',SYSDATE,36.12345677,123.23124155,'N');


SELECT US.U_NO, US.U_NAME, US.U_PHONE, SH.D_NO, DR.D_PROFILE, DR.D_REGION, DR.D_NAME, DR.D_BIRTH, DR.D_GENDER, DR.D_TITLE, DR.D_CONTENT, SH.U_NO, SH.S_SEQ, SH.S_DATE, SH.S_TIME, SH.S_LOCATION, SH.S_COURSE, SH.S_PEOPLE, SH.S_PRICE, SH.S_REGDATE, SH.S_LATITUDE, SH.S_LONGITUDE, SH.S_CONFIRMED_CHECK
	FROM SCHEDULE_TABLE SH
	INNER JOIN DRIVER_TABLE DR
	ON SH.D_NO = DR.D_NO
	INNER JOIN USER_TABLE US
	ON SH.U_NO = US.U_NO
	INNER JOIN RATING_TABLE RA
	ON SH.D_NO = RA.D_NO
	WHERE SH.D_NO = 2
	GROUP BY RA.RA_RATING;
	

SELECT AVG(RA_RATING) FROM RATING_TABLE WHERE D_NO = 7; 

DELETE FROM SCHEDULE_TABLE;