DROP TABLE REVIEWBOARD;
DROP SEQUENCE R_NO_SEQ;

CREATE SEQUENCE R_NO_SEQ;
CREATE TABLE REVIEWBOARD(
	R_NO NUMBER PRIMARY KEY,
	R_WRITER VARCHAR2(100) NOT NULL,
	R_TITLE VARCHAR2(2000) NOT NULL,
	R_CONTENT VARCHAR2(4000) NOT NULL,
	R_AREA VARCHAR2(100) NOT NULL,
	R_DATE DATE NOT NULL,
	R_HIT NUMBER NOT NULL,
	R_RECOMMEND NUMBER NOT NULL
)

INSERT INTO REVIEWBOARD VALUES(R_NO_SEQ.NEXTVAL, '이효홍', '테스트', '테스트 중임', '서울', SYSDATE, 0, 0);
INSERT INTO REVIEWBOARD VALUES(R_NO_SEQ.NEXTVAL, 'test', '테스트', '테스트 중', '서울', SYSDATE, 0, 0);
SELECT * FROM REVIEWBOARD;

DELETE FROM REVIEWBOARD WHERE R_NO = 21;

DROP TABLE QNABOARD;
DROP SEQUENCE Q_BOARDNO_SEQ;
DROP SEQUENCE Q_GROUPNO_SEQ;


CREATE SEQUENCE Q_BOARDNO_SEQ;
CREATE SEQUENCE Q_GROUPNO_SEQ;

CREATE TABLE QNABOARD(
	Q_BOARDNO NUMBER PRIMARY KEY,
	Q_GROUPNO NUMBER NOT NULL,
	Q_GROUPSQ NUMBER NOT NULL,
	Q_TITLETAB NUMBER NOT NULL,
	Q_WRITER VARCHAR2(100) NOT NULL,
	Q_TITLE VARCHAR2(2000) NOT NULL,
	Q_CONTENT VARCHAR2(4000) NOT NULL,
	Q_DATE DATE NOT NULL,
	Q_ISDELETE VARCHAR2(10) NOT NULL,
	Q_COUNT NUMBER NOT NULL
)
